### ISSUE TITLE
OOM with parser options: {allowTypes: true}

### ISSUE THREAD

**Issue by aladdin-add** [kataw/kataw#102]
![image](https://user-images.githubusercontent.com/13050025/121763288-5aca1900-cb6d-11eb-9302-eea8c5aa304f.png)

**Comment by KFlash** [comment]
This is the test you pointing at that should cause OOM. I can't trigger this issue

![adsfkjldakljafdslksa](https://user-images.githubusercontent.com/31855118/121763395-60742e80-cb6e-11eb-97ee-c2c434f40751.png)

**Comment by KFlash** [comment]
I manually parsed each test in that folder you are pointing to and no one trigger OOM. Where is the failing test case?

**Comment by aladdin-add** [comment]
(ノへ￣、)it's not the one, but the next. if a test case is causing OOM, the cst is not returned, and no output.

**Comment by aladdin-add** [comment]
try this: 
```js
type a = ((({(): string => T},) => T));
```

**Comment by KFlash** [comment]
Ah yeah that one give me 'Identifier expected(23, 26)'. So  I need to fix it, but no OOM

**Comment by KFlash** [comment]
@aladdin-add Try to autogenerate again

**Comment by aladdin-add** [comment]
great! it's working fine after rebase the main branch. will merge that one.
