### ISSUE TITLE
WIP! implement new printer and get comments 100% correct

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#129]
This is *WIP*.

cc / @aladdin-add The goal is to replace Prettier?

**Comment by KFlash** [comment]
@aladdin-add  Should we document the comment algorithm or just keep it internal?  I got it working 100% now, but it's so super sensitive...

This will not be attached correctly in Prettier, but one whitespace wrong and the comment will not be attached !

```ts
if /* comment 1 */ (/* comment 2 */x/* comment 3 */) {/* comment 4 */} // comment 5
```

**Comment by KFlash** [comment]
@aladdin-add  This comment cannot be printed in Prettier and generate an error

```ts
debugger/* comment */; 
```
Can you report it on the Prettier issue tracker?

**Comment by aladdin-add** [comment]
sure! // cc @fisker

**Comment by aladdin-add** [comment]
_Should we document the comment algorithm or just keep it internal? I got it working 100% now, but it's so super sensitive..._

IMO, no need to document it unless it was a public API - it's likely we will change it in later releases.

**Comment by KFlash** [comment]
I go through this now step-by-step and create tests for each single comment, so this will take time. Soon done with statements

**Comment by KFlash** [comment]
@aladdin-add We need to merge the transformer code with printer code - let this 2 share the same main object. This because the unique ID that is created inside transformers are stuck on that object, and we need it in the printer to generate unique names.

Any ideas on how we can do this, and can you test the transformer code in the test runner?

**Comment by KFlash** [comment]
@aladdin-add As a "drive by" I'm now also printing types.

Here is an example on a declared function with type annotation decorated with comments

![types](https://user-images.githubusercontent.com/31855118/122689819-179c3400-d258-11eb-8d9e-2c227877611f.png)

**Comment by KFlash** [comment]
@aladdin-add I'm running comment tests now vs Prettier with Prettier own tests. I'm **100% sure** we have no comment issues and all comments attached on correct places - even before and after punctuators. Prettier suffers with this.

**Comment by KFlash** [comment]
@aladdin-add [Test this demo](https://kataw.github.io/kataw/kataw_print/) and let me know where I screwed up when it comes to comment. Statement level should be okay now and I'm working through the rest.

**Comment by KFlash** [comment]
@aladdin-add [Test this demo](https://kataw.github.io/kataw/kataw_print/) and let me know where I screwed up when it comes to comment. Statement level should be okay now and I'm working through the rest.

I finally see the end of this now

**Comment by KFlash** [comment]
Closing this as solved. No code released yet, need to fix pretty printing.
