### ISSUE TITLE
put the type snapshots in a separate folder

### ISSUE THREAD

**Issue by aladdin-add** [kataw/kataw#134]
```bash
snapshots
├── ecma262
       ├── parser
       ├── printer
├── types
       ├── parser
       ├── printer

```

**Comment by KFlash** [comment]
Good idea! Can you re-arrange? I'm in the middle of some printer refactoring

**Comment by KFlash** [comment]
How would you separate out the printer tests? Refactor the test runner?

**Comment by aladdin-add** [comment]
not related to the tests, just move the snapshots.  I think it will helpful we want to test some of them, e.g. `ts-node -f snapshots/ecma262` to only the js snapshots.

can you take it? :)

**Comment by KFlash** [comment]
can't you give it a try? I have just spent 24 hours non-stop without break in front of this screen fixing a printer, transformer and visitor :P I need to take a few hours off now
