### ISSUE TITLE
Implement CLI and kataw ignore comment

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#141]
Implement CLI and kataw ignore comment

**Comment by KFlash** [comment]
@aladdin-add The 'kataw-ignore' comment is tricky. How should it be implemented?

Let say we want to format this one

`a ? a / b ? b : c : a ? b : a ? a / b ? b : c : a ? b : a ? a / b ? b : c : a ? b : c`

Without  ignore comment the result will be

```ts
a
  ? a = b
    ? b
    : c
  : a
    ? b
    : a
      ? a = b
        ? b
        : c
      : a
        ? b
        : a
          ? a = b
            ? b
            : c
          : a
            ? b
            : c;
```

**but** if I add an ignore comment,

```ts
 // kataw-ignore
      a ? a / b ? b : c : a ? b : a ? a / b ? b : c : a ? b : a ? a / b ? b : c : a ? b : c
```

The result will be the same as input.

This is tricky because we need to add bitwise masks to the `NodeFlags` on each literal CST node and identifier node. And in an `ConditionalExpression` we need to check the left side of the first node.

**Comment by KFlash** [comment]
Need to make an list overview over what should be allowed to be ignored because I have to do this manually.

We could add Babel to that list :)

**Comment by aladdin-add** [comment]
not sure I'm following. I didn't see how it's tricky.  not just need to ignore the next node of the `kataw-ignore`.
why check the left side?

**Comment by KFlash** [comment]
If we have an conditional expression and it starts with an identifier. The ignore comment will be the one to contain the 'NodeFlag'

'a ? b : c'. 

The first node is an identifier and in this case we need to check he 'node.shortCircut'.

**Comment by KFlash** [comment]
I adjusted some of the 'NodeFlags' now so conditional and binary expression inherit the 'NodeFlags' from "left" side. This should allow us to ignore them, plus blocks, arrows, function and class.

What else do we need to ignore?

**Comment by KFlash** [comment]
@aladdin-add  You should be aware that if we ignore then we ignore :)  Everything between the two CST nodes we ignore - e.g. conditional expression - will be a 1:1  replicate of original source. This includes formatting, comment, whitespace etc.

Prettier can't do that, but we can because of how we handle whitespace and loc tracking.

**Comment by aladdin-add** [comment]
I see! IMO, the ignore comments should only exists before a block/statement/expression. not inside of an expression.

so, the entire expression should be ignored, in your example

**Comment by KFlash** [comment]
So how we do it with member expr, class, function etc? If you ignore an function, same thing will happen. Should we allow just to ignore the func body or param list?  The format will be weird

**Comment by aladdin-add** [comment]
yes, the entire function should be ignored. I just mean not allow a part of a statement.

e.g.
```js
a ? //kataw-ignore
b : c ? a : b;
```

it seems not particularly useful, and maybe hard to implement.

**Comment by KFlash** [comment]
Is that something Prettier support and something we should support? 

It's not hard. If you follow me then you already know that the ignore comment has been attached to the identifier 'b' in your example, so just do a slice from that pos to end of node pos. The formatting will be weird 👍

**Comment by KFlash** [comment]
Question now is what we do with type annotations? If you ignore a function the type annotation will also be ignored.

**Comment by aladdin-add** [comment]
it makes sense to ignore them too.

**Comment by KFlash** [comment]
As  you requested:

Ignored

```ts
     a ? //kataw-ignore
      b : /* aladdin */ c ? a : b;
 ```
 
 Source code

 ```ts 
 export function printConditionalExpression(
  printer: Printer,
  node: any,
  parentNode: SyntaxNode,
  lineMap: number[]
): any {

  if (node.flags & NodeFlags.IgnoreNextNode) {
    return printer.source.slice(node.start, node.end)
  }

  // Checking for the 'IgnoreNextNode' on the 'consequent' property allows
  // Kataw to ignore formatting after the 'shortCircuit' property
  //
  //  a ? // kataw-ignore
  //  b : c ? a : b;
  //
  if (node.consequent.flags & NodeFlags.IgnoreNextNode) {
    return printer.source.slice(node.consequentstart, node.end)
  }

  const printed = concat([
    printStatements(printer, node.shortCircuit, node, lineMap),
    indent(
      concat([
        line,
        '?',
        ' ',
        node.consequent.kind === SyntaxKind.ConditionalExpression
          ? printStatements(printer, node.consequent, node, lineMap)
          : indent(printStatements(printer, node.consequent, node, lineMap)),
        line,
        ':',
        ' ',
        node.alternate.kind === SyntaxKind.ConditionalExpression
          ? printStatements(printer, node.alternate, node, lineMap)
          : indent(printStatements(printer, node.alternate, node, lineMap)),
      ])
    ),
  ]);

  return parentNode.kind === SyntaxKind.ConditionalExpression
    ? printed
    : group(printed, {});
}
 ```

**Comment by KFlash** [comment]
@aladdin-add Can you give me a list or an overview over what Kataw should be allowed to ignore?

**Comment by aladdin-add** [comment]
examples:
```js
// kataw-ignore
var foo;

// kataw-ignore
foo.bar();

// kataw-ignore
if(foo){
    //...
}

// kataw-ignore
function foo(){
    
}

// kataw-ignore
class Foo{
    //...
}


class Foo(){
    // kataw-ignore
    foo = 0;

    // kataw-ignore
    static bar = 0;

    // kataw-ignore
    quz(){
        //...
    }
}


// kataw-ignore (for, while, do..while, try..catch)
for(i = 0; i < 10; i++){
    //...
}

```

**Comment by aladdin-add** [comment]
to clarify: I slightly suggest not allowing inside an expression. image such a case:

![image](https://user-images.githubusercontent.com/13050025/124362930-c97d2c80-dc6a-11eb-944f-dfcc0b22c6e6.png)

you want to ignore what color?

**Comment by KFlash** [comment]
In your example ( the picture) where do you think the ignore bitwise mask is? It's on the parenthesize expression node - '()'. So in that case the ignore will start from opening paren '(' and all the way until it find identifier 'c'.

**Comment by KFlash** [comment]
but the ignore comment is only allowed as a single line comment - not a block comment. Same as Prettier I think.

**Comment by aladdin-add** [comment]
ah, didn't noticed that! it also makes sense.

**Comment by KFlash** [comment]
I need to do some RL stuff now, but will continue on this soon.

**Comment by KFlash** [comment]
@aladdin-add Kataw now ignore everything as expected. I hope at least. What about options?

**Comment by KFlash** [comment]
"smart format" should be turned off by default?

**Comment by KFlash** [comment]
@aladdin-add Can you create a CLI and use the 'the beast' branch as the base?

**Comment by KFlash** [comment]
@aladdin-add Can you create a CLI and use the Pr you opened as the base? 

And can you give me an list over the options that I need to add? I'm done with the ignore comment list. It works now!

**Comment by KFlash** [comment]
@aladdin-add I'm closing this. Soon 1 month no action and most of this is done
