### ISSUE TITLE
test runner - printed VALID code is INVALID

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#142]
The test runner claim that valid printed code is invalid. This is a HUGE problem for me. Currently stuck with over 4000 files with this issue.

**Input**
```ts
class A { foo(a, b,) {} };
```

**Printed**
```ts
class A {
  foo(
    a,
    b,
  ){}
}
```

**Comment by KFlash** [comment]
I can add to this issue that it sometimes it "feels like" I'm dealing with two different parsers. Same settings and same parser in a local test environment as used in the test runner output different CST so hard to track where the issues is.

**Comment by aladdin-add** [comment]
maybe it's the parser's issue? the message means printed code diagnostics's length not equal with the input's.

https://github.com/kataw/kataw/blob/496f8e3f513d74b927200827aa94a8d7e3590e8b/test/runner/tob.ts#L65

**Comment by KFlash** [comment]
How can it be a parser issue? I'm also verify the output manually against the parser. No issue

**Comment by KFlash** [comment]
If it's the parser then it brings me to the second discovery  - that it feels sometimes I'm dealing with two parses. See my comment above

**Comment by aladdin-add** [comment]
how can I repro the issue? did you push the change?

**Comment by KFlash** [comment]
I can't push it, but it sometimes happen with current code online. The printer. For example the printer - through the test runner - accepted to print this invalid code - `a?.?.b`.  It was not caught at all. 

see one of my latest commit to the repo to throw error for that case.

Here the 'chain' property is null because it's invalid. The test runner didn't pick it up. It should be invalid to reparse it.

**Comment by KFlash** [comment]
And my current Kataw code locale I can't even push it to Kataw repo because it will break. The tests will fail. But locale it they all pass and no errors.

**Comment by aladdin-add** [comment]
can you push it to another branch?

**Comment by KFlash** [comment]
What to push? I gave an example in first comment, and explained how it printed invalid code.

**Comment by KFlash** [comment]
The code I'm playing with locale catch all this issues that's why I report them and found this test runner issue. Just now the test runner generated a 100 MB file that I was forced to delete.

**Comment by KFlash** [comment]
@aladdin-add What do you want? Do you want the 'the best"? Wait!

**Comment by aladdin-add** [comment]
"best"?

please push your branch to the gh, so I was able to repro it!

**Comment by KFlash** [comment]
"The beast" is the name I use on my private printer. It's an Prettier equal code that I play around with.

It's incoming!

**Comment by aladdin-add** [comment]
it was working on my local, too. I will create a PR to test it.

**Comment by KFlash** [comment]
Also change the 'tob.ts' back to use the original printer and it breaks tests even the code is correct.

**Comment by KFlash** [comment]
@aladdin-add Here is how you can reproduce

1. Use 'the beast' and print the code with 'allowArrowParens' enabled

It should transform 'async x=>x, y' into 'async (x)=>x, y', but nothing happens and it report that 'async x=>x, y' is an invalid code!

Turn off the option and suddenly 'async x=>x, y' is valid code!

**Comment by aladdin-add** [comment]
if you try to re-parse the printed code, you will get `Declaration or statement expected`. it's why it was treated as `invalid`.

I think we just need to improve the error message.

**Comment by KFlash** [comment]
Can you improve the error message? I will have a look at the parser code for async

**Comment by KFlash** [comment]
Closing as the mention option works now. It was an error with async arrow parsing. Fixed!
