### ISSUE TITLE
Implement printer options

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#150]
Implement this options:

- [x]  'printWidth'
- [x]  ''tabWidth'
- [x]  'useTabs'
- [x]  'noSemicolon'
- [x] ''singleQuote
- [x] ''noWhitespace
- [x] ''compact"
- [x] ''noObjectCurlySpacing"
- [x] ''arrayBracketSpacing"
- [ ] ''disallowStringEscape"
- [x] ''allowArrowParens"
- [x] ''spaceAfterAt"
- [x] ''endOfLine"

There are no option for trailing comma. The printer follows the 'WYSIWYG' principle and the output is 1:1 to original source plus pretty printing. Trailing commas will be added if they exist in the source.

@aladdin-add others? We have 18 more slots available so we can add 18 more options.

**Comment by aladdin-add** [comment]
![image](https://user-images.githubusercontent.com/13050025/125018079-f2585400-e0a6-11eb-898a-4a85f9b53db7.png)


can you implement the options as prettier (except for the parser/vue/...)?

**Comment by KFlash** [comment]
Isn't this options for the CLI? I implemented some of them.

**Comment by KFlash** [comment]
@aladdin-add I implemented a simple `quoteProps` option now.  If on it will quote the object props with double quote. If you add the `singleQuote`  it will quote the props with single quotes. I skipped 'preserve'. Just avoid to apply that option and it's "preserved" 👍

**Comment by KFlash** [comment]
If you 'insertPragma' you will get this output


```ts
/**
 * @kataw
 */

class C {
  set X(v = 0) {}
  static set X(v2 = 0) {}
}
```

**Comment by KFlash** [comment]
This is the options supported by Kataw's printe:

- printWidth
-  tabWidth
- useTabs
- noSemicolon
- singleQuote
- noWhitespace
- compact
- noObjectCurlySpacing
- arrayBracketSpacing
- disallowStringEscape
- allowArrowParens
- spaceAfterAt
- quoteProps
- coerceQuoteProps
- insertPragma
- endOfLine

**Comment by KFlash** [comment]
Closing as done.
