### ISSUE TITLE
The test runner goes crazy - 100 MB files

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#153]
I working on options for the printer. When I set a global bitwise mask - that is not related to anything- the test runner add extra spaces in the printer output and created over 340 files with a size of 100 MB each.

The diff is then too large to commit

How to reproduce? I'm not sure. I don't have enough experience to understand how a bitwise mask can cause a test runner to act like this. In my world it's impossible. The bitwise mask is part of the printer.ts code and isolated.

![100mb](https://user-images.githubusercontent.com/31855118/125198204-82f38780-e293-11eb-968e-66643b362b3c.png)

**Comment by aladdin-add** [comment]
there is a noticeably big issue in the printer(main branch). look at `\test\__snapshot__\ecma262\expressions\arrow\gen\condiional_paren_middle\x0028interfacex0029_x003dx003e_x007b_x0027use_strictx0027_0_x007d.md`, the printed code is extremely too long.

**Comment by KFlash** [comment]
I see, but why does the test runner generate that long file?

**Comment by KFlash** [comment]
Did you get any 100 mb files if you try to run it on a windows computer?

**Comment by aladdin-add** [comment]
that's highly likely to be a bad-formatted md file. I would suggest switch from windows to linux/wsl. :)

**Comment by KFlash** [comment]
my other work require windows, so it's easier if you  just fix the test runner issue ;)

**Comment by KFlash** [comment]
Closing. Seems to fixed itself.
