### ISSUE TITLE
Test runner creates random 100 MB files

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#154]
Out of the blue and for no reason the test runner creates 100 MB files on windows. No idea how to reproduce it. It just happen when the test runner feel for it.

Was improving printing of decorators. Ran the tests as normal and the test file that has decorators increased to 100 MB

**Comment by KFlash** [comment]
This is not related to #153 and the filename is not long either. 

![runner](https://user-images.githubusercontent.com/31855118/125201952-edacbf00-e2a3-11eb-86e6-f13384563964.png)

**Comment by KFlash** [comment]
@aladdin-add can you fix this?

**Comment by KFlash** [comment]
@aladdin-add Any solution for this issue?

**Comment by aladdin-add** [comment]
it's very likely the md was incorrectly formatted.

**Comment by KFlash** [comment]
How to "fix" the md. The files are auto-gen. And see the other issue. No issue with the names

**Comment by aladdin-add** [comment]
well, I will try to repro it on my windows in a few days.

**Comment by KFlash** [comment]
Closing. Seems to fixed itself.
