### ISSUE TITLE
Test runner playing with backticks

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#155]
I'm improving template parsing and ran the tests through the test runner on this repo and discovered that some additional back ticks has been added.

The funny thing is that the test case has no back ticks in it. So nothing related to template parsing

![asdjfasfd](https://user-images.githubusercontent.com/31855118/126036177-1780bbea-1f02-4751-a8eb-42dacdc4a796.png)

**Comment by aladdin-add** [comment]
sounds like a bug, but hard to tell. please provide the exact command and the input.

**Comment by KFlash** [comment]
The tests is the same as found in the repo. The cmd I used was  'test:update-all'.

**Comment by KFlash** [comment]
Closing. Seems to fixed itself.
