### ISSUE TITLE
replace prettier with kataw's pretty printer

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#16]
Just a reminder for  now until  the printer has been open sourced.

**Comment by aladdin-add** [comment]
should we add a kataw-cli, with supporting something like pretter.config.js/prettierignore ？

**Comment by KFlash** [comment]
We should, and also find a way to implement ignore comments. I'm not there *yet*.

**Comment by KFlash** [comment]
A demo of the  soon open sourced printer can be tested [here](https://kataw.github.io/kataw/kataw_print/). Still WIP!

**Comment by KFlash** [comment]
@aladdin-add How should we do it with a ignore comment as in Pretter?  

I have started to enable comments in the printer - see the demo - but it will take me maybe 7 more days to finish.

**Comment by aladdin-add** [comment]
the easiest way I can imagine is: storing the node's raw text when parsing, and in the printer(code gen) phrase, just skip the node, and put the raw text back.

e.g.
```js
// kataw-ignore
foo()
```

=> {nodeKind: xxx, raw: "foo"},

**Comment by aladdin-add** [comment]
better to look at how prettier get it. :)

**Comment by KFlash** [comment]
We already save the raw data by default. When times come maybe  you can look into it ?

**Comment by KFlash** [comment]
@aladdin-add Something like this?

![ignore](https://user-images.githubusercontent.com/31855118/110858070-99dd9980-82f4-11eb-8154-9fdfcc985a71.png)
