### ISSUE TITLE
Infinity was stringified to null.

### ISSUE THREAD

**Issue by aladdin-add** [kataw/kataw#23]
1234567890e1234567890 was parsed to Infinity,  then stringified to null in the md.

do you think the text should be `"1234567890e1234567890 "`?

![image](https://user-images.githubusercontent.com/13050025/111038595-d4feda80-8464-11eb-9c04-125adf8526cc.png)

https://github.com/kataw/kataw/blob/8481d92a10dc3a197048e432d2c73224bef0989a/test/__snapshot__/compiler/js/lexer/numbers/decimal2.md#L490

**Comment by KFlash** [comment]
The parser result is he correct one, so I guess it's a test runner issue again.

**Comment by aladdin-add** [comment]
the problem is NaN/Infinity  is not a valid value in JSON.

 to make it work, I made a little change to my `deepEqual`: https://github.com/kataw/kataw/blob/cb21935dd1809b057684989e0bedc18cb6ebb90d/test/runner/utils.ts#L79-L83

**Comment by KFlash** [comment]
@aladdin-add I guess this is solved?
