### ISSUE TITLE
autogenerated files getting git info mixed with invalid char

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#28]
autogenerated files getting git info mixed with invalid char as part of the generated test case

See attached picture regarding latest commit

![pull](https://user-images.githubusercontent.com/31855118/111165505-11a01280-85da-11eb-864b-3e5f0de13d15.png)

**Comment by aladdin-add** [comment]
the conflicts from my update(unix style path) and your update(windows style path) v(o_ _)ﾉ

**Comment by KFlash** [comment]
how can the changed end up in the .md file? Need to be removed 👍

**Comment by aladdin-add** [comment]
no worries, I can re gen these cases.
