### ISSUE TITLE
(node:18296) Warning: 

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#30]
(node:18296) Warning: Label 'Running 11266 test cases. Total time' already exists for console.time()

**Comment by KFlash** [comment]
(node:18296) Warning: No such label 'Running 11266 test cases. Total time' for console.timeEnd()

**Comment by KFlash** [comment]
@aladdin-add Can you look into this?

**Comment by aladdin-add** [comment]
is this still an issue? I'm not seeing the warning in latest main.

**Comment by aladdin-add** [comment]
https://github.com/kataw/kataw/runs/2147586791

**Comment by KFlash** [comment]
I haven't seen it either. closing
