### ISSUE TITLE
running prettier throws

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#31]
Tried to run prettier 

> git merge-base HEAD main
> git diff --name-only --diff-filter=ACMRTUB b5d3e6bb665c5ebe459a5da226798b0cb0a31b7a
node:child_process:712
    throw err;
    ^

<ref *1> Error: spawnSync git ENOBUFS
    at Object.spawnSync (node:internal/child_process:1086:20)
    at spawnSync (node:child_process:676:24)
    at execFileSync (node:child_process:703:15)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32) {
  errno: -4060,
  code: 'ENOBUFS',
  syscall: 'spawnSync git',
  path: 'git',
  spawnargs: [
    'diff',
    '--name-only',
    '--diff-filter=ACMRTUB',
    [ 'b5d3e6bb665c5ebe459a5da226798b0cb0a31b7a' ]
  ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    '.eslintrc.js\n' +
      '.gitattributes\n' +
      '.npmrc\n' +
      '.prettierignore\n' +
      '.vscode/launch.json\n' +
      '.vscode/settings.json\n' +
      'LICENSE.md\n' +
      'README.md\n' +
      'package-lock.json\n' +
      'package.json\n' +
      'scripts/bump-dev-version.js\n' +
      'scripts/generate-unicode.js\n' +

**Comment by aladdin-add** [comment]
didn't repro it. how and which branch get this error?

**Comment by KFlash** [comment]
both master and the branch I made for the PR

**Comment by KFlash** [comment]
closed as fixed.
