### ISSUE TITLE
Use of exit code output NPM msg if snapshot  mismatch 

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#35]
Use of exit code gives this message now if snapshot  mismatch 
Output mismatch for D:\kataw\test\__snapshot__/compiler/ts/contextualExpressionTypecheckingDoesntBlowStack.md
Output mismatch for D:\kataw\test\__snapshot__/compiler/ts/nestedLoops.md
Running 11257 test cases. Total time: 7.180s
Mismatch: 7/11257
exit code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kataw@0.0.12 test: `ts-node test/cli`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kataw@0.0.12 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by aladdin-add** [comment]
the reason I added it is: I was running the tests not using `npm`, but `npx`. e.g.
```bash
npx ts-node test/cli.ts -u
```

I think it's fine if we are alway using npm, just remove this line:

https://github.com/kataw/kataw/blob/6ad95158a19f5f3d4cfdf608e232cfb67c869fb6/test/cli.ts#L16

**Comment by KFlash** [comment]
I let you remove that line  :)
