### ISSUE TITLE
type error in test runner

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#44]
test/cli.ts:30:111 - error TS2322: Type 'number' is not assignable to type '{ label: number; sent: () => any; trys: any[]; ops: any[]; }'.

30                     if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }

**Comment by aladdin-add** [comment]
can you describe how you get this error, and the raw output?

**Comment by KFlash** [comment]
I simply wrote a test and tried to test it.  Then the test runner froze and after a few sec that messages pop sup. I got confused because '30 if (!(t = _.trys, t = t.length > 0' has nothing to do with Kataw source code or the test runner.

I modified the tests, and it works now except I need to update all the time. Normal testing are broken - always complaining about mismatch.

Anyway. This is common TS issue. I guess related to something in ts-node library

**Comment by KFlash** [comment]
I was wrong. It points to some code in ts-lib. Not ts-node.

**Comment by KFlash** [comment]
@aladdin-add It's related to async/await

https://github.com/TypeStrong/ts-node/issues/774

**Comment by KFlash** [comment]
I tried to run coverage

test/cli.ts:30:111 - error TS2322: Type 'number' is not assignable to type '{ label: number; sent: () => any; trys: any[]; ops: any[]; }'.

30                     if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                                                                                                                 ~
  at createTSError (D:\x\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (D:\x\node_modules\ts-node\src\index.ts:517:19)

**Comment by aladdin-add** [comment]
the code was compiled twice? https://github.com/TypeStrong/ts-node/issues/774#issuecomment-605070430

but why? I was not able to repro on my macos, can you share the command that you used to run?

**Comment by KFlash** [comment]
I only tried to run code coverage. 'npm run coverage'

**Comment by aladdin-add** [comment]
not sure why. maybe another "windows-compat" issue. ╮(￣▽￣)╭

a workaround could be setting "target" to >="es2017", to avoid compiling async functions to regenerator.

**Comment by KFlash** [comment]
@aladdin-add is there a fix for this? And what's the test runner update?
