### ISSUE TITLE
test-runner destroys .md tests with nonsense

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#47]
@aladdin-add  Look at this test. Something is wrong :)

https://github.com/kataw/kataw/blob/cst-parser/test/__snapshot__/parser/declarations/function/type-parameters.md

**Comment by aladdin-add** [comment]
the link is to 404 :-(

**Comment by KFlash** [comment]
https://github.com/kataw/kataw/blob/5f44c97f7c24842d09796323e1a93cd22b3da785/test/__snapshot__/parser/declarations/function/type-parameters.md

**Comment by KFlash** [comment]
Can you try fix all the tests in the open PR? It's around 7k mismatch :(

**Comment by aladdin-add** [comment]
seems you are using `\r\n` again. :))

**Comment by aladdin-add** [comment]
+ 569f653bc9a953e7ec1c356b5b4db62f188f8f38 updated all the tests
+ e7ccbb07a972e28a5ce37c9da4bed2f216908e3c fixes the test

**Comment by KFlash** [comment]
which branch is the tests fixed?

**Comment by aladdin-add** [comment]
https://github.com/kataw/kataw/tree/fix/tests

or you can just cherry-pick the 2 commits to your branch. :)

**Comment by aladdin-add** [comment]
just pushed a commit to fix other failing tests: bfb47f9109d49862ba04b75d2f4129c7f9238ffc

**Comment by KFlash** [comment]
I will look at it, but try update directly on the cst-parser branch.  Still 125 mismatch

**Comment by aladdin-add** [comment]
I just pushed a commit to fixed the test failing, and also fixed a bad import.

sounds the issue can be closed. :)

**Comment by KFlash** [comment]
I'm closing. And the PR should be ready within 1 week
