### ISSUE TITLE
extend test runner to print errors

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#51]
With the upcoming refactoring of the Kataw parser, the error handling is an callback func. So it's needed to extend the
test runner to print in each '.md' errors if they are returned by the cb.

As of now we will never know if any error diagnostics has been thrown

**Comment by aladdin-add** [comment]
will look into it!

**Comment by KFlash** [comment]
It should be easy. if any value returned by the CB, print it in the .md file

**Comment by KFlash** [comment]
@aladdin-add The Kataw parser is complicated, but I'm getting there soon
