### ISSUE TITLE
find a way to test AST walker and API

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#53]
Need to find a way to test the CST walker and the public API methods. They can be used together

```ts
kataw.forEachChild(rootNode, visitor);

function visitor(node) {

   // check if the node has any children
   if (!kataw.isChildLess(node)) {
  return kataw.forEachChild(node, visitor);
  }
}
```

**Comment by KFlash** [comment]
@aladdin-add  How can we test this?

**Comment by KFlash** [comment]
@aladdin-add Can you extend the test runner to test this?

**Comment by KFlash** [comment]
I'm using the `NodeFlags` internal, but we still need to find a way to check if all nodes got them set correctly

**Comment by KFlash** [comment]
@aladdin-add Not possible to solve?

**Comment by aladdin-add** [comment]
working on this!

**Comment by KFlash** [comment]
I got a issue with a sick kid, but soon online again. How you solve it? You may need to adjust the walker code to get it working.

**Comment by KFlash** [comment]
@aladdin-add friendly ping

**Comment by KFlash** [comment]
@aladdin-add  friendly ping

**Comment by KFlash** [comment]
Closing this as done. And regarding the API - #113
