### ISSUE TITLE
test-262 compat

### ISSUE THREAD

**Issue by aladdin-add** [kataw/kataw#54]
refs: https://github.com/tc39/test262

**Comment by KFlash** [comment]
I'm working on it. Can you write here the missing cases?

**Comment by KFlash** [comment]
I know lexical bindings have to be fixed, and I got released a slot for it so I will implement this after the PR has been merged.

Except that. What other cases do you know about?

Test the parser here: https://kataw.github.io/kataw/kataw_ast/

**Comment by KFlash** [comment]
@aladdin-add I think declaration and statement parsing now should be test-262 compat. I still have to "walk through" expressions.
There are a few non-solved cases left, but not that important I think. PR welcome :)

**Comment by KFlash** [comment]
@aladdin-add Should be 90% compat now. Lexical still a TODO

**Comment by KFlash** [comment]
@aladdin-add friendly ping. Can you verify if this is solved?

**Comment by KFlash** [comment]
Closing as solved. It may be a few cases left to fix, but will fix them while improving perf.

The parser can be tested here to verify if  it's test-262 compat 

https://kataw.github.io/kataw/kataw_ast/
