### ISSUE TITLE
test runner transformer valid chars into invalid chars

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#55]
Try this  case:  'class C { #👍 }' it get transformed into  'class C { #@{x1f44d}@ };'

**Comment by aladdin-add** [comment]
it seems be expected - all these chars were encoded to something like `{x...}`.
do you mean removing this behavior?

https://github.com/kataw/kataw/blob/61b4fa90a19ebedc5b35822d8ea16a5ed5700bc0/test/runner/utils.ts#L57-L60

**Comment by KFlash** [comment]
i think remove yes if safe

**Comment by aladdin-add** [comment]
a potential drawback if doing so: some chars cannot be printed in the md, e.g. 0-width chars

**Comment by KFlash** [comment]
no workarounds?
