### ISSUE TITLE
forEachChild not working as expected

### ISSUE THREAD

**Issue by aladdin-add** [kataw/kataw#61]
![image](https://user-images.githubusercontent.com/13050025/116646204-16622f80-a9aa-11eb-8f8a-3ebd3f99f575.png)

--
the result was from https://kataw.github.io/kataw/kataw_ast/

**Comment by KFlash** [comment]
@aladdin-add Seems like it do some strange things if it's find a empty array - []. I didn't test empty array lit. Can you test that and provide a fix if it's not working?
