### ISSUE TITLE
test runner prints invalid syntax

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#68]
The test runner accept CST nodes with invalid syntax to be printed. Need to use the callback here and only allow printing if valid syntax. That should be inline with Prettier

**Comment by KFlash** [comment]
You can see it here:

![printed_error](https://user-images.githubusercontent.com/31855118/117220594-19da3880-ae3a-11eb-8cdb-84110bbc2052.png)

**Comment by KFlash** [comment]
@aladdin-add  This is a huge problem. Take this case ` fo\u0072 = x;`. It get printed into `for(; ; )`. It's actually invalid syntax

**Comment by aladdin-add** [comment]
in non-error-recovery mode, please do not ignore the errors silently! just throw the errors?

**Comment by KFlash** [comment]
A printer shouldn't run in a error-recovery mode. Can you add a error handler in the test runner for this?

**Comment by KFlash** [comment]
`bar ? (, => {}) : baz;` throws on `null` because the `:` token doesn't exist in the CST tree.

**Comment by KFlash** [comment]
@aladdin-add  this is how I do it locally

```ts
    const source = parse("bar ? (, => {}) : baz;",
      'root',
      Context.None,
      false,
      { allowTypes: true },
      function (a: any, b: any, c: any, d: any) {
        throw b + '(' + c + ', ' + d + ')';
      }
    );
    console.log(printSourceFile(source));
```

**Comment by KFlash** [comment]
closing as fixed in the printer PR
