### ISSUE TITLE
test runner isn't consistent 

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#96]
After adding the progress bar it will still output 'Running 18941 test cases. Total time: 7.454s'

The tests have been run so maybe change to "Ran x test cases"?

The 'Total time' is different than what you see on the progress bar.

Autogenerate files suggest ''run test:update'. That command doesn't exist

**Comment by KFlash** [comment]
@aladdin-add Look at this nice picture :)

Linebreak after the progress bar is missing, and maybe add colors to make the differences clear? Green for progress? Red for mismatch?

![adsadjladasdas](https://user-images.githubusercontent.com/31855118/121535395-b6dd5200-ca34-11eb-9331-f10bc6e9a5cd.png)

**Comment by aladdin-add** [comment]
closing as fixed.
