### ISSUE TITLE
progress bar issues

### ISSUE THREAD

**Issue by KFlash** [kataw/kataw#99]
Type 'typeof ProgressBar' has no construct signatures.

18   const bar = new ProgressBar('Testing snapshots [:bar] :percent, :elapseds elapsed, eta :etas,', {
                     ~~~~~~~~~~~

  test/cli.ts:6:1
    6 import * as ProgressBar from 'progress';
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.

**Comment by aladdin-add** [comment]
how did you get the error?

**Comment by KFlash** [comment]
I don't know. It suddenly showed up while I was writing tests
